### ISSUE TITLE
Enormous amount of tiny WAL segments on S3

### ISSUE THREAD

**Issue by taburet** [slatedb/slatedb#192] opened 2024-09-10 09:14 UTC
Running the code below on EC2-S3 combo with slatedb 0.1.4. Usually it works good for the first 5-10 seconds, then something bad happens and almost every `put` results in a separate tiny WAL segment being written to S3. If `get`s are removed from the mix, it apparently works good. It also works good locally (performance isn't great, though), probably some latency from EC2 to S3 is much lower and that's inducing the problem. I was able to reproduce it only on a real EC2 instance.

```rust
use object_store::aws::{DynamoCommit, S3ConditionalPut};
use object_store::{path::Path, ObjectStore};
use rand::{Rng, RngCore};
use slatedb::config::ReadLevel::Uncommitted;
use slatedb::config::{DbOptions, ReadOptions, WriteOptions};
use slatedb::db::Db;
use std::sync::Arc;
use std::time::{Duration, Instant};

#[tokio::main]
async fn main() {
    let options = DbOptions::default();
    let object_store: Arc<dyn ObjectStore> = Arc::new(
        object_store::aws::AmazonS3Builder::new()
            .with_access_key_id(std::env::var("AWS_ACCESS_KEY_ID").unwrap())
            .with_secret_access_key(std::env::var("AWS_SECRET_ACCESS_KEY").unwrap())
            .with_bucket_name(std::env::var("AWS_S3_BUCKET").unwrap())
            .with_region(std::env::var("AWS_REGION").unwrap())
            .with_conditional_put(S3ConditionalPut::Dynamo(DynamoCommit::new(
                std::env::var("AWS_DYNAMODB_TABLE").unwrap(),
            )))
            .build()
            .unwrap(),
    );
    let db = Db::open_with_opts(Path::from("store3"), options, object_store)
        .await
        .unwrap();

    let mut random = rand::thread_rng();
    let mut value = vec![0; 8 * 1024];
    rand::thread_rng().fill_bytes(value.as_mut_slice());

    let start = Instant::now();
    let duration = Duration::from_secs(10 * 60);
    while start.elapsed() < duration {
        let key: u32 = random.gen_range(0..10_000);
        // 20% write
        if random.gen_range(0..100) < 20 {
            db.put_with_options(
                &key.to_be_bytes(),
                value.as_slice(),
                &WriteOptions {
                    await_durable: false,
                },
            )
            .await;
        } else {
            db.get_with_options(
                &key.to_be_bytes(),
                &ReadOptions {
                    read_level: Uncommitted,
                },
            )
            .await
            .unwrap();

            // usual reads inducing the problem too
            // db.get(&key.to_be_bytes()).await.unwrap();
        }
    }

    db.close().await.unwrap();
}
```

<img width="1753" alt="Screenshot 2024-09-09 at 19 45 38" src="https://github.com/user-attachments/assets/40f7dce5-3f1e-4ece-a870-3c66e3a51854">

**Comment by taburet** [comment] 2024-09-12 08:07
The issue is caused by the mixed read-write load and slow reads, basically there are no enough writes to fill the WAL segment fully. Local disk cache should help once implemented.

**Comment by flaneur2020** [comment] 2024-09-12 08:16
the local cache has already been merged to the main branch, can you have a try like this?

```
foyer = { git = "https://github.com/slatedb/slatedb", rev = "795b794" }
```

to enable the local cache, you can set up a dir folder for it like:

```
    let options = DbOptions {
        object_store_cache_options: ObjectStoreCacheOptions {
             root_folder: Some(std::path::PathBuf::from("/tmp/mycache"))
             part_size: 4 * 1024 * 1024
        },
    };
```

**Comment by taburet** [comment] 2024-09-12 11:29
With 25% writes, block cache and object cache enabled I get this:

```
[ec2-user@ip-172-31-17-203 src]$ cargo run
   Compiling slatedb-s3 v0.1.0 (/home/ec2-user/slatedb-s3)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 10.47s
     Running `/home/ec2-user/slatedb-s3/target/debug/slatedb-s3`
19099.809 put/s, 57204.428 get/s, 76304.237 op/s, elapsed 1.000009997s
4467.721 put/s, 13249.879 get/s, 17717.600 op/s, elapsed 1.200388342s
13.882 put/s, 46.272 get/s, 60.153 op/s, elapsed 1.296685521s
35.984 put/s, 166.304 get/s, 202.288 op/s, elapsed 1.028235196s
69.693 put/s, 204.100 get/s, 273.793 op/s, elapsed 1.004409907s
78.133 put/s, 236.377 get/s, 314.510 op/s, elapsed 1.011097269s
63.381 put/s, 181.367 get/s, 244.748 op/s, elapsed 1.025545474s
61.990 put/s, 181.049 get/s, 243.039 op/s, elapsed 1.016297699s
47.141 put/s, 145.353 get/s, 192.494 op/s, elapsed 1.018212008s
67.902 put/s, 229.896 get/s, 297.798 op/s, elapsed 1.030899843s
32.499 put/s, 100.451 get/s, 132.950 op/s, elapsed 1.015416488s
38.853 put/s, 149.436 get/s, 188.290 op/s, elapsed 1.003772752s
79.319 put/s, 231.266 get/s, 310.585 op/s, elapsed 1.046413004s
61.928 put/s, 191.776 get/s, 253.704 op/s, elapsed 1.001166891s
43.502 put/s, 128.572 get/s, 172.074 op/s, elapsed 1.034437832s
59.915 put/s, 186.735 get/s, 246.650 op/s, elapsed 1.001420602s
58.727 put/s, 205.064 get/s, 263.791 op/s, elapsed 1.038701458s
27.048 put/s, 97.516 get/s, 124.564 op/s, elapsed 1.404902713s
Killed
```

Apparently object cache is also leaking memory and got `Killed` by OS. With block cache only, the throughput is 100-150 op/s and it can run for long time without memory leaks.

**Comment by flaneur2020** [comment] 2024-09-12 11:32
the object store cache is exepcted to be stateless, i guess the oom kill might caused by OS's Page Cache eat up all the available memory, which is annoying, let me figure out some ways to mitigate it 🤔

**Comment by flaneur2020** [comment] 2024-09-12 11:35
I guess it might be because the page cache did not get flushed in time during writes, making the unrecyclable page cache accumulated too much. let me fix it

**Comment by flaneur2020** [comment] 2024-09-12 11:48
before the pr get merged, you can have a try with the following config in `Cargo.toml` and check whether the oom will still happen or not:

```
slatedb = { git = "https://github.com/flaneur2020/slatedb", rev = "73f0497" }
```

**Comment by taburet** [comment] 2024-09-12 11:54
if it can help, `htop` looks like this:

<img width="1643" alt="Screenshot 2024-09-12 at 13 51 01" src="https://github.com/user-attachments/assets/d029f1a7-9234-4ea6-b07b-4e29e4da55d7">

**Comment by taburet** [comment] 2024-09-12 12:02
tested it on https://github.com/slatedb/slatedb/pull/201, it didn't help with the leak

**Comment by flaneur2020** [comment] 2024-09-12 12:14
weird, i'd try make a reproduce in my laptop maybe with some memory dumps

(have no available s3 storage at my hand, i'll use a local fs to mock the object storage)

**Comment by taburet** [comment] 2024-09-12 12:23
Here is the code I use currently:

```rust
use object_store::aws::{DynamoCommit, S3ConditionalPut};
use object_store::{path::Path, ObjectStore};
use rand::{Rng, RngCore};
use slatedb::config::ReadLevel::Uncommitted;
use slatedb::config::{DbOptions, ObjectStoreCacheOptions, ReadOptions, WriteOptions};
use slatedb::db::Db;
use slatedb::inmemory_cache::InMemoryCacheOptions;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::{Duration, Instant};

#[tokio::main]
async fn main() {
    let mut options = DbOptions::default();
    options.wal_enabled = false;

    let mut block_cache_options = InMemoryCacheOptions::default();
    block_cache_options.max_capacity = 128 * 1024 * 1024;
    block_cache_options.cached_block_size = 1024;
    options.block_cache_options = Some(block_cache_options);

    let mut object_cache_options = ObjectStoreCacheOptions::default();
    object_cache_options.root_folder = Some(PathBuf::from("/tmp/mycache"));
    object_cache_options.part_size_bytes = 4 * 1024 * 1024;
    options.object_store_cache_options = object_cache_options;

    // let object_store: Arc<dyn ObjectStore> = Arc::new(object_store::memory::InMemory::new());
    let object_store: Arc<dyn ObjectStore> = Arc::new(
        object_store::aws::AmazonS3Builder::new()
            .with_access_key_id(std::env::var("AWS_ACCESS_KEY_ID").unwrap())
            .with_secret_access_key(std::env::var("AWS_SECRET_ACCESS_KEY").unwrap())
            .with_bucket_name(std::env::var("AWS_S3_BUCKET").unwrap())
            .with_region(std::env::var("AWS_REGION").unwrap())
            .with_conditional_put(S3ConditionalPut::Dynamo(DynamoCommit::new(
                std::env::var("AWS_DYNAMODB_TABLE").unwrap(),
            )))
            .build()
            .unwrap(),
    );

    let db = Db::open_with_opts(Path::from("store2375"), options, object_store)
        .await
        .unwrap();

    let mut random = rand::thread_rng();
    let mut value = vec![0; 8 * 1024];
    rand::thread_rng().fill_bytes(value.as_mut_slice());

    let duration = Duration::from_secs(10 * 60);
    let mut puts = 0;
    let mut gets = 0;
    let start = Instant::now();
    let mut last_update = start;
    while start.elapsed() < duration {
        let elapsed_from_update = last_update.elapsed();
        if elapsed_from_update >= Duration::from_secs(1) {
            last_update = Instant::now();

            println!(
                "{:.3} put/s + {:.3} get/s = {:.3} op/s, {:.3} s elapsed",
                puts as f64 / elapsed_from_update.as_secs_f64(),
                gets as f64 / elapsed_from_update.as_secs_f64(),
                (puts + gets) as f64 / elapsed_from_update.as_secs_f64(),
                elapsed_from_update.as_secs_f64()
            );
            puts = 0;
            gets = 0;
        }

        let key: u32 = random.gen_range(0..100_000);
        if random.gen_range(0..100) < 25 {
            puts += 1;
            db.put_with_options(
                &key.to_be_bytes(),
                value.as_slice(),
                &WriteOptions {
                    await_durable: false,
                },
            )
            .await;
        } else {
            gets += 1;
            db.get_with_options(
                &key.to_be_bytes(),
                &ReadOptions {
                    read_level: Uncommitted,
                },
            )
            .await
            .unwrap();
        }
    }

    db.close().await.unwrap();
}
```

**Comment by flaneur2020** [comment] 2024-09-12 12:56
reproduced in my local machine, indeed vast amount of RES were allocated:

![Screenshot 2024-09-12 at 20 55 41](https://github.com/user-attachments/assets/2d8ed8e9-9c93-4de3-8033-543282a78e00)

**Comment by flaneur2020** [comment] 2024-09-12 14:07
i suspect that the memory leaks also exists with object cache disabled, through it's leaked MUCH slower...

this is my script with two minor modification:

1. use local fs
2. disable the object store's cache


```
use object_store::aws::{DynamoCommit, S3ConditionalPut};
use object_store::local::LocalFileSystem;
use object_store::{path::Path, ObjectStore};
use rand::{Rng, RngCore};
use slatedb::config::ReadLevel::Uncommitted;
use slatedb::config::{DbOptions, ObjectStoreCacheOptions, ReadOptions, WriteOptions};
use slatedb::db::Db;
use slatedb::inmemory_cache::InMemoryCacheOptions;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::{Duration, Instant};

#[global_allocator]
static GLOBAL: jemallocator::Jemalloc = jemallocator::Jemalloc;

#[tokio::main]
async fn main() {
    let mut options = DbOptions::default();
    options.wal_enabled = false;

    let mut block_cache_options = InMemoryCacheOptions::default();
    block_cache_options.max_capacity = 128 * 1024 * 1024;
    block_cache_options.cached_block_size = 1024;
    options.block_cache_options = Some(block_cache_options);

    let mut object_cache_options = ObjectStoreCacheOptions::default();
    // object_cache_options.root_folder = Some(PathBuf::from("/tmp/mycache"));
    // object_cache_options.part_size_bytes = 4 * 1024 * 1024;
    options.object_store_cache_options = object_cache_options;

    // let object_store: Arc<dyn ObjectStore> = Arc::new(object_store::memory::InMemory::new());
    let object_store = Arc::new(LocalFileSystem::new_with_prefix("/tmp/debug").unwrap());

    let db = Db::open_with_opts(Path::from("store2375"), options, object_store)
        .await
        .unwrap();

    let mut random = rand::thread_rng();
    let mut value = vec![0; 8 * 1024];
    rand::thread_rng().fill_bytes(value.as_mut_slice());

    let duration = Duration::from_secs(10 * 60);
    let mut puts = 0;
    let mut gets = 0;
    let start = Instant::now();
    let mut last_update = start;
    while start.elapsed() < duration {
        let elapsed_from_update = last_update.elapsed();
        if elapsed_from_update >= Duration::from_secs(1) {
            last_update = Instant::now();

            println!(
                "{:.3} put/s + {:.3} get/s = {:.3} op/s, {:.3} s elapsed",
                puts as f64 / elapsed_from_update.as_secs_f64(),
                gets as f64 / elapsed_from_update.as_secs_f64(),
                (puts + gets) as f64 / elapsed_from_update.as_secs_f64(),
                elapsed_from_update.as_secs_f64()
            );
            puts = 0;
            gets = 0;
        }

        let key: u32 = random.gen_range(0..100_000);
        if random.gen_range(0..100) < 25 {
            puts += 1;
            db.put_with_options(
                &key.to_be_bytes(),
                value.as_slice(),
                &WriteOptions {
                    await_durable: false,
                },
            )
            .await;
        } else {
            gets += 1;
            db.get_with_options(
                &key.to_be_bytes(),
                &ReadOptions {
                    read_level: Uncommitted,
                },
            )
            .await
            .unwrap();
        }
    }

    db.close().await.unwrap();
}
```

**Comment by flaneur2020** [comment] 2024-09-12 15:33
it let me feels that the malloced memory were not returned to os in time, and the object store cache are bigger parts (4mb), makes the memory buffer consumed even faster...

i'm considering directly mmap these local files data to avoid `malloc()`, it's ugly but maybe worth a try. if the memory still keeps growing, there must be something else wrong.

**Comment by criccomini** [comment] 2024-09-13 03:35
Want to point out that #186 seems to be suffering from OOM as well. You can run db bench with:

```
db-bench --provider memory --path /home/zamazan4ik/open_source/slatedb/target/storage --disable-wal true write --duration 25000 --key-len 32 --val-len 256
```

It will fail within 30s with:

```
Stats Dump:
---------------------------------------
records written: 0
write rate: 0/second over 0ns

Stats Dump:
---------------------------------------
records written: 3467312
write rate: 346731.2/second over 10s

Stats Dump:
---------------------------------------
records written: 6356508
write rate: 317825.4/second over 20s

thread 'tokio-runtime-worker' panicked at src/sst_iter.rs:189:47:
join task failed: JoinError::Cancelled(Id(3416))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Shutdown error in compaction task: JoinError::Panic(Id(2046), "join task failed: JoinError::Cancelled(Id(3416))", ...)
```

I watched the memory usage go from 3GiB to 5 GiB in a matter of seconds. It died shortly after.

**Comment by flaneur2020** [comment] 2024-09-13 14:55
i tested the script https://gist.github.com/flaneur2020/bd03c6d9032828c379a86c7ddeb8db32 again with this pr https://github.com/slatedb/slatedb/pull/211, and the oom issue could be fixed on my local machine.

can you help a retry with the following config in Cargo.toml? thanks a lot

```
slatedb = { git = "https://github.com/flaneur2020/slatedb", rev = "8011a47" }
```

**Comment by taburet** [comment] 2024-09-13 15:37
appears to be working good now, the memory consumption is still slowly growing with time, like 1-5 MB/s, but that's probably expected, before it was like 0.5-1 GB/s

**Comment by criccomini** [comment] 2024-09-13 21:59
Sorry, I think I fat fingered something, which closed this issue. I'm leaving it open until #211 is merged.

**Closed** 2024-09-14 22:24 UTC
Labels: bug
