### ISSUE TITLE
Write operations have side effects that are not apparent to users

### ISSUE THREAD

**Issue by calavera** [slatedb/slatedb#283] opened 2024-10-26 01:52 UTC
**Describe the bug**
I’ve noticed that write operations like `put_with_options` can panic, but it’s not really apparent to users. One of Rust’s benefits are the safety guarantees that the language provides. However, by allowing certain operations to panic, SlateDb is kinda not providing those guarantees.

I think it might be worth considering having a strong bias towards being more idiomatic, returning errors, and preventing processes from panicking.

**To Reproduce**
For example, if you try to write an entry with an empty key, the process will panic.

**Expected behavior**
I would expect write operations to return results with errors when an operation cannot be completed for any kind of internal invariant.

If this is something that people want to address, I can take a stab at it.

**Comment by criccomini** [comment] 2024-10-28 18:08
Yes, I believe the panics are there right now because we haven't exposed `SlateDbError`s to the end user yet. I think the intent was to fix this as part of #111. It's been several weeks since @palash25 has engaged with that issue. Do you want to take a crack at it?

**Comment by criccomini** [comment] 2024-10-28 18:09
(I'm going to close this as a dupe of #111. @calavera LMK if you want me to assign #111 to you.)

**Closed by criccomini** 2024-10-28 18:09 UTC
Labels: bug

**Comment by palash25** [comment] 2024-10-28 18:19
Yes please go ahead I wasn't able to find time to wrap it up. I will pick some other issue later.
